;;; Package Repository for GNU Guix
;;; Copyright © 2026 Franz Geffke <mail@gofranz.com>

(define-module (px services usbguard)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages hardware)
  #:use-module (gnu services)
  #:use-module (gnu services dbus)
  #:use-module (gnu services shepherd)
  #:use-module (gnu system shadow)
  #:use-module (guix gexp)
  #:use-module (guix records)
  #:use-module (ice-9 match)
  #:use-module (srfi srfi-1)
  #:export (usbguard-configuration
            usbguard-configuration?
            usbguard-configuration-package
            usbguard-configuration-rule-file
            usbguard-configuration-rule-folder
            usbguard-configuration-implicit-policy-target
            usbguard-configuration-present-device-policy
            usbguard-configuration-present-controller-policy
            usbguard-configuration-inserted-device-policy
            usbguard-configuration-authorized-default
            usbguard-configuration-restore-controller-device-state?
            usbguard-configuration-device-manager-backend
            usbguard-configuration-ipc-allowed-users
            usbguard-configuration-ipc-allowed-groups
            usbguard-configuration-device-rules-with-port?
            usbguard-configuration-audit-backend
            usbguard-configuration-audit-file-path
            usbguard-configuration-hide-pii?
            usbguard-configuration-log-file
            usbguard-configuration-auto-start?
            usbguard-service-type))

;;;
;;; USBGuard — USB device authorization policy framework.
;;;
;;; Runs the usbguard-daemon, which enforces a whitelist of USB devices
;;; based on rules.  The daemon's configuration file is generated in the
;;; store and passed via -c, keeping it immutable and reproducible.  The
;;; policy rules themselves live under /etc/usbguard/ — a plain (non-store)
;;; directory created by activation — so the daemon can persist rules
;;; added via IPC and so admins can edit rules.conf the traditional way.
;;; This mirrors how gnu/services/networking.scm handles NetworkManager's
;;; /etc/NetworkManager/system-connections/.
;;;

(define-record-type* <usbguard-configuration>
  usbguard-configuration make-usbguard-configuration
  usbguard-configuration?
  (package
   usbguard-configuration-package
   (default usbguard))
  (rule-file
   usbguard-configuration-rule-file
   (default "/etc/usbguard/rules.conf"))
  (rule-folder
   usbguard-configuration-rule-folder
   (default "/etc/usbguard/rules.d/"))
  (implicit-policy-target
   usbguard-configuration-implicit-policy-target
   (default 'block))                    ;one of 'allow 'block 'reject
  (present-device-policy
   usbguard-configuration-present-device-policy
   (default 'apply-policy))             ;allow block reject keep apply-policy
  (present-controller-policy
   usbguard-configuration-present-controller-policy
   (default 'keep))                     ;allow block reject keep apply-policy
  (inserted-device-policy
   usbguard-configuration-inserted-device-policy
   (default 'apply-policy))             ;block reject apply-policy
  (authorized-default
   usbguard-configuration-authorized-default
   (default 'none))                     ;keep none all internal
  (restore-controller-device-state?
   usbguard-configuration-restore-controller-device-state?
   (default #f))
  (device-manager-backend
   usbguard-configuration-device-manager-backend
   (default 'uevent))                   ;uevent umockdev
  (ipc-allowed-users
   usbguard-configuration-ipc-allowed-users
   (default '("root")))                 ;list of usernames
  (ipc-allowed-groups
   usbguard-configuration-ipc-allowed-groups
   (default '()))                       ;list of groupnames
  (device-rules-with-port?
   usbguard-configuration-device-rules-with-port?
   (default #f))
  (audit-backend
   usbguard-configuration-audit-backend
   (default 'FileAudit))                ;FileAudit LinuxAudit
  (audit-file-path
   usbguard-configuration-audit-file-path
   (default "/var/log/usbguard/usbguard-audit.log"))
  (hide-pii?
   usbguard-configuration-hide-pii?
   (default #f))
  (log-file
   usbguard-configuration-log-file
   (default "/var/log/usbguard.log"))
  (auto-start?
   usbguard-configuration-auto-start?
   (default #t)))

(define (bool->string b)
  (if b "true" "false"))

(define (usbguard-config-file config)
  (match-record config <usbguard-configuration>
    (rule-file rule-folder implicit-policy-target present-device-policy
     present-controller-policy inserted-device-policy authorized-default
     restore-controller-device-state? device-manager-backend
     ipc-allowed-users ipc-allowed-groups device-rules-with-port?
     audit-backend audit-file-path hide-pii?)
    (plain-file
     "usbguard-daemon.conf"
     (string-append
      "# Generated by usbguard-service-type.\n"
      "RuleFile=" rule-file "\n"
      "RuleFolder=" rule-folder "\n"
      "ImplicitPolicyTarget=" (symbol->string implicit-policy-target) "\n"
      "PresentDevicePolicy=" (symbol->string present-device-policy) "\n"
      "PresentControllerPolicy=" (symbol->string present-controller-policy) "\n"
      "InsertedDevicePolicy=" (symbol->string inserted-device-policy) "\n"
      "AuthorizedDefault=" (symbol->string authorized-default) "\n"
      "RestoreControllerDeviceState="
      (bool->string restore-controller-device-state?) "\n"
      "DeviceManagerBackend=" (symbol->string device-manager-backend) "\n"
      "IPCAllowedUsers=" (string-join ipc-allowed-users " ") "\n"
      "IPCAllowedGroups=" (string-join ipc-allowed-groups " ") "\n"
      "IPCAccessControlFiles=/etc/usbguard/IPCAccessControl.d/\n"
      "DeviceRulesWithPort=" (bool->string device-rules-with-port?) "\n"
      "AuditBackend=" (symbol->string audit-backend) "\n"
      "AuditFilePath=" audit-file-path "\n"
      "HidePII=" (bool->string hide-pii?) "\n"))))

(define %usbguard-accounts
  ;; The daemon runs as root (needs CAP_CHOWN/CAP_FOWNER/CAP_DAC_READ_SEARCH
  ;; to flip USB authorization bits in sysfs).  The 'usbguard' group exists
  ;; purely so it can be named in IPCAllowedGroups to give desktop users
  ;; access to the IPC socket without running the GUI as root.
  (list (user-group
         (name "usbguard")
         (system? #t))))

(define (usbguard-activation config)
  (let ((rule-file (usbguard-configuration-rule-file config))
        (rule-folder (usbguard-configuration-rule-folder config))
        (audit-file (usbguard-configuration-audit-file-path config)))
    #~(begin
        (use-modules (guix build utils))
        ;; /etc/usbguard/: owned by root, mode 0700.  The daemon needs to
        ;; read/write rules.conf when rules are added via IPC, and admins
        ;; edit it directly.  Created here (not via etc-service-type) so
        ;; it's a plain directory, not a store symlink.
        (mkdir-p "/etc/usbguard")
        (chmod "/etc/usbguard" #o700)
        (mkdir-p #$rule-folder)
        (chmod #$rule-folder #o700)
        (mkdir-p "/etc/usbguard/IPCAccessControl.d")
        (chmod "/etc/usbguard/IPCAccessControl.d" #o700)
        ;; Seed an empty rules file if none exists.  With ImplicitPolicyTarget
        ;; set to 'block (the default), an empty file means "block everything
        ;; that isn't explicitly allowed" — the safe starting state.
        (unless (file-exists? #$rule-file)
          (call-with-output-file #$rule-file
            (lambda (port)
              (display "# USBGuard rules.  Managed by usbguard-daemon.\n"
                       port)))
          (chmod #$rule-file #o600))
        ;; Audit log directory.
        (mkdir-p (dirname #$audit-file)))))

(define (usbguard-shepherd-service config)
  (let ((pkg (usbguard-configuration-package config))
        (conf (usbguard-config-file config))
        (log-file (usbguard-configuration-log-file config))
        (auto-start? (usbguard-configuration-auto-start? config)))
    (list
     (shepherd-service
      (documentation "Run the usbguard-daemon for USB device authorization.")
      (provision '(usbguard))
      (requirement '(user-processes udev))
      (auto-start? auto-start?)
      ;; Do NOT pass -f: that flag enables classical daemon forking.
      ;; Shepherd needs the process to stay in the foreground.
      (start #~(make-forkexec-constructor
                (list #$(file-append pkg "/sbin/usbguard-daemon")
                      "-k"          ;log to console (captured by shepherd)
                      "-C"          ;drop capabilities after startup
                      "-W"          ;apply a seccomp syscall allowlist
                      "-c" #$conf)
                #:log-file #$log-file))
      (stop #~(make-kill-destructor))
      (actions (list (shepherd-configuration-action conf)))))))

(define usbguard-service-type
  (service-type
   (name 'usbguard)
   (description "Run the USBGuard daemon, which enforces a USB device
authorization policy.  Also registers the USBGuard D-Bus configuration and
Polkit action so that @command{usbguard-dbus} and desktop front-ends can
talk to the daemon.")
   (extensions
    (list (service-extension shepherd-root-service-type
                             usbguard-shepherd-service)
          (service-extension account-service-type
                             (const %usbguard-accounts))
          (service-extension activation-service-type
                             usbguard-activation)
          (service-extension dbus-root-service-type
                             (compose list usbguard-configuration-package))
          (service-extension polkit-service-type
                             (compose list usbguard-configuration-package))
          (service-extension profile-service-type
                             (compose list usbguard-configuration-package))))
   (default-value (usbguard-configuration))))
